# Generated by Django 3.2.5 on 2021-07-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0003_auto_20210712_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='levels',
            name='follow_artist',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Follow Artist'),
        ),
        migrations.AddField(
            model_name='levels',
            name='url_steam_workshop_author',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Creator Workshop'),
        ),
    ]
