<<<<<<< Updated upstream
# Generated by Django 3.2.5 on 2021-07-12 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 3.2.9 on 2021-11-15 18:03

from django.db import migrations, models
>>>>>>> Stashed changes


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< Updated upstream
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> Stashed changes
    ]

    operations = [
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< Updated upstream
                ('name_level', models.CharField(max_length=20, verbose_name='Name levels')),
                ('rating', models.IntegerField(default=0, verbose_name='Reating')),
                ('diffculty', models.CharField(choices=[('Easy', 'Easy'), ('Normal', 'Normal'), ('Hard', 'Hard'), ('Expert', 'Expert'), ('Expert+', 'Expert+')], max_length=20, verbose_name='Diffcuty')),
                ('content', models.TextField(max_length=1024, verbose_name='Content')),
                ('levels_file', models.FileField(blank=True, upload_to='levels_file/%Y/%m/%d/', verbose_name='Levels file')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('preview', models.ImageField(blank=True, upload_to='preview_levels/%Y/%m/%d/', verbose_name='Preview image')),
                ('level_by', models.CharField(max_length=150, null=True, verbose_name='Level By')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('author_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
=======
                ('name_level', models.CharField(max_length=120, verbose_name='Name levels')),
                ('rating', models.IntegerField(default=0, verbose_name='Reating')),
                ('autthor_level', models.CharField(max_length=80, verbose_name='Author')),
                ('diffculty', models.CharField(choices=[('Easy', 'Easy'), ('Normal', 'Normal'), ('Hard', 'Hard'), ('Expert', 'Expert'), ('Expert+', 'Expert+')], max_length=20, verbose_name='Diffcuty')),
                ('content', models.TextField(verbose_name='Content')),
                ('levels_file', models.FileField(upload_to='levels_file/%Y/%m/%d/', verbose_name='Levels file')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('preview', models.ImageField(blank=True, upload_to='preview_levels/%Y/%m/%d/', verbose_name='Preview image')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
>>>>>>> Stashed changes
            ],
            options={
                'verbose_name': 'Level',
                'verbose_name_plural': 'Levels database',
                'ordering': ['-created_at'],
            },
        ),
    ]
