# Generated by Django 3.2.9 on 2021-11-21 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_level', models.CharField(max_length=20, verbose_name='Name levels')),
                ('rating', models.IntegerField(default=0, verbose_name='Reating')),
                ('diffculty', models.CharField(choices=[('basic', 'basic'), ('moderate', 'moderate'), ('advanced', 'advanced'), ('master', 'master'), ('expert', 'expert')], max_length=20, verbose_name='Diffcuty')),
                ('content', models.TextField(max_length=1024, verbose_name='Content')),
                ('levels_file', models.FileField(blank=True, upload_to='levels_file/%Y/%m/%d/', verbose_name='Levels file')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('preview', models.ImageField(blank=True, upload_to='preview_levels/%Y/%m/%d/', verbose_name='Preview image')),
                ('level_by', models.CharField(max_length=150, null=True, verbose_name='Level By')),
                ('url_getsong', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Song url')),
                ('url_steam_workshop_author', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Creator Workshop')),
                ('follow_artist', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Follow Artist')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('author_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Level',
                'verbose_name_plural': 'Levels database',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(verbose_name='Text comment')),
                ('object_id', models.PositiveIntegerField()),
                ('like_count', models.IntegerField(default=0, verbose_name='Like')),
                ('Dislike_count', models.IntegerField(default=0, verbose_name='Dislike')),
                ('heart_comments', models.BooleanField(default=False, verbose_name='Heart')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='Date craeted comments')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_children', to='levels.comment', verbose_name='Parent comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author comment')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
