# Generated by Django 3.2.5 on 2021-07-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='levels',
            name='url_getsong',
            field=models.CharField(max_length=1000, null=True, verbose_name='Song'),
        ),
    ]
