# Generated by Django 3.2.5 on 2021-07-12 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('levels', '0002_levels_url_getsong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levels',
            name='url_getsong',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Song url'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(verbose_name='Text comment')),
                ('object_id', models.PositiveIntegerField()),
                ('like_count', models.IntegerField(default=0, verbose_name='Like')),
                ('Dislike_count', models.IntegerField(default=0, verbose_name='Dislike')),
                ('heart_comments', models.BooleanField(default=False, verbose_name='Heart')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='Date craeted comments')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_children', to='levels.comment', verbose_name='Parent comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author comment')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
